# Generated by Django 4.0.2 on 2022-05-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KillswithcSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_compatible_msg', models.TextField(default='La versión actual de su aplicación es muy antigua. Por favor, actualiza a una versión nueva desde la tienda.', max_length=1000, verbose_name='Non compatible message')),
                ('upgradable_compatible_msg', models.TextField(default='¡Hay una actualización disponible! Descarga la actualización cuanto antes para que puedas disfrutar de las nuevas funciones y mejoras que tenemos para tí', max_length=1000, verbose_name='Upgradable but compatible message')),
                ('last_version_msg', models.CharField(default='Su aplicación está actualizada', max_length=1000, verbose_name='Last version message')),
            ],
        ),
    ]
