# Generated by Django 4.0.2 on 2022-03-30 21:20

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category name')),
                ('color', colorfield.fields.ColorField(default='#808080', image_field=None, max_length=18, samples=None, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='MediaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.TextField(max_length=100, verbose_name='Site name (human readable)')),
                ('scraper', models.CharField(choices=[('la_patilla', 'La Patilla'), ('efecto_cocuyo', 'Efecto cocuyo'), ('unknown', 'unknown')], max_length=100, verbose_name='Scraper (its identifier)')),
                ('site_url', models.URLField(max_length=300, verbose_name='Site url')),
                ('name', models.TextField(max_length=100, unique=True, verbose_name='Site name')),
                ('site_url_image', models.URLField(max_length=300, null=True, verbose_name='Site image')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Scraped date')),
                ('title', models.TextField(max_length=200, verbose_name='Title')),
                ('datetime', models.DateTimeField(null=True, verbose_name='Publication name')),
                ('excerpt', models.TextField(default='Excerpt', max_length=300, null=True)),
                ('image_url', models.URLField(max_length=300, verbose_name='Image source')),
                ('url', models.URLField(max_length=300, unique=True, verbose_name='Full article url')),
                ('relevance', models.BooleanField(default=None, null=True, verbose_name='Relevance')),
                ('categories', models.ManyToManyField(to='scraper.ArticleCategory')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.mediasite')),
            ],
        ),
    ]
