# Generated by Django 4.0.2 on 2022-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasite',
            name='scraping_active',
            field=models.BooleanField(default=True, verbose_name='Scraping active'),
        ),
    ]
