# Generated by Django 4.0.2 on 2022-03-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleheadline',
            old_name='date',
            new_name='datetime',
        ),
    ]
