# Generated by Django 4.0.2 on 2022-02-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleheadline",
            name="categories",
            field=models.ManyToManyField(to="scraper.ArticleCategory"),
        ),
    ]
