# Generated by Django 4.0.2 on 2022-04-08 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_mediasite_scraping_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediasite',
            name='last_scraped',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Last time scraped'),
        ),
        migrations.AddField(
            model_name='mediasite',
            name='scraping_frequency_mins',
            field=models.IntegerField(default=5, verbose_name='Scraping frequency (minutes)'),
        ),
        migrations.AlterField(
            model_name='mediasite',
            name='scraper',
            field=models.CharField(choices=[('la_patilla', 'La Patilla'), ('efecto_cocuyo', 'Efecto cocuyo')], max_length=100, verbose_name='Scraper (its identifier)'),
        ),
    ]
