# Generated by Django 4.0.2 on 2022-04-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_mediasite_last_scraped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleheadline',
            name='image_url',
            field=models.URLField(max_length=300, null=True, verbose_name='Image source'),
        ),
        migrations.AlterField(
            model_name='mediasite',
            name='scraper',
            field=models.CharField(choices=[('la_patilla', 'La Patilla'), ('efecto_cocuyo', 'Efecto cocuyo'), ('el_nacional', 'El Nacional'), ('cronica_uno', 'Crónica Uno'), ('runrunes', 'Runrunes')], max_length=100, verbose_name='Scraper (its identifier)'),
        ),
    ]
