# Generated by Django 4.0.2 on 2022-05-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_articleheadline_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='editors_choice',
            field=models.BooleanField(default=False, verbose_name="Is Editor's choice"),
        ),
        migrations.AddField(
            model_name='articleheadline',
            name='editors_choice',
            field=models.BooleanField(default=False, verbose_name="Editor's choice"),
        ),
    ]
