# Generated by Django 4.0.2 on 2022-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_articlecategory_editors_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasite',
            name='scraper',
            field=models.CharField(choices=[('la_patilla', 'La Patilla'), ('efecto_cocuyo', 'Efecto cocuyo'), ('el_nacional', 'El Nacional'), ('cronica_uno', 'Crónica Uno'), ('runrunes', 'Runrunes'), ('el_pitazo', 'El Pitazo')], max_length=100, verbose_name='Scraper (its identifier)'),
        ),
    ]
