# Generated by Django 4.0.2 on 2022-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
