# Generated by Django 4.0.2 on 2022-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_player', '0002_audio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[('News', 'News'), ('Podcast', 'Podcast')], default='News', max_length=25),
        ),
    ]
